/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_royran_timebref_ssl_RpmSSL */

#ifndef _Included_com_royran_timebref_ssl_RpmSSL
#define _Included_com_royran_timebref_ssl_RpmSSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_royran_timebref_ssl_RpmSSL
 * Method:    encryptBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_royran_timebrief_ssl_RpmSSL_encryptBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_royran_timebref_ssl_RpmSSL
 * Method:    decryptBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_royran_timebrief_ssl_RpmSSL_decryptBytes
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
